{% set name = "dmf-chip" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sci-bots/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 1dc9d12d4ce05344bc28064db4deef5629144da218f1973503d1c6c6132f265b

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - dmf-chip = dmf_chip.__main__:main

requirements:
  host:
    - python
    - pip
  run:
    - click
    - click-log
    - funcsigs
    - logging-helpers
    - lxml
    - networkx
    - pandas
    - pint
    - python
    - semantic_version
    - shapely
    - six

test:
  imports:
    - dmf_chip

about:
  home: http://github.com/sci-bots/dmf-chip
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: 'Digital microfluidic chip tools'

extra:
  recipe-maintainers:
    - cfobel
