{% set name = "dmf-chip" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sci-bots/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 5990904601392c3ab832e0caa43def329efeae1e220e25f32c0697b2ba19e7c1

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - dmf-chip = dmf_chip.__main__:main

requirements:
  host:
    - python
    - pip
  run:
    - click
    - click-log
    - funcsigs
    - logging-helpers
    - lxml
    - networkx
    - pandas
    - pint
    - python
    - semantic_version
    - shapely
    - six

test:
  imports:
    - dmf_chip

about:
  home: http://github.com/sci-bots/dmf-chip
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: 'Digital microfluidic chip tools'

extra:
  recipe-maintainers:
    - cfobel
