travis:
  secure:
    BINSTAR_TOKEN: TIWi9Kb1lxHK9huej0I/sK8M2H5sJf9YeWw08qU7BAqppjQRjUzSCIRlW74vcgUq05eJQMRQokJJXgTWc9b7RxOLUM89rZ/yN6kVkGBB+qn/fEGc0iCDNtu8AeqvhJiyrKcm4uU4SZBF47S9j98E1W2ZklWD8YdqUae1YYATW8Ngau1sTaUPbloB5ybwsEZOKZJVXlpk4Ff8zSynQO0hjh6yNOVlL7XYfyccapQl53iP4j7YW51JmYIEdW67DL0dxdy3CUOZmU18YYTei7mu1z/msGMLhlMLdXEzfS2tOrxt8Wtr791LIAetk3bb0O6cN0SriDn+Byy0r01Sl5JP71yzuWNaRttV0+F4DHYOmzQOpDAHnHr1KAEKTHDdE5MX2mxPOrLAachq0T4FLbM4AMWLY2AhMbrHbWG/1G93iyAJuLAPqSH7NdOz/xy+yo78v3fAnNrRaw8DB5pIGY2cfB8x1KtZFVtZO+oCA944L5rd193kq6iHXiFzMKrQuLqEzUAmBpNfQdOvODyi6tHcKOPP3v57/QfR5Uab4W1AhQlvXd1kFAj+HVVtYYFNcjslB0Z04Bqm1Y9cVZgBX0R6Dc9beUvYvn2UkDPkxdUAXWsTMllb3VY6rL8pNkDqaWhi2kmLq67fHVioc39u7I9m2Dr/+vL50Ppkp0h+5zLYGdw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
